use serde_json::json;
/// Authenticated AO2 Control Plane route metadata shared by the route-index handler and tests.
///
/// Keep this catalog free of credential material. It describes observer/API surfaces only;
/// it never grants release authority and never advertises token-bearing URLs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RouteMetadata {
    pub method: &'static str,
    pub path: &'static str,
    pub category: &'static str,
    pub owner: &'static str,
    pub download: bool,
    pub portable: bool,
    pub mutates_observer_storage: bool,
}

impl RouteMetadata {
    pub fn to_json(self) -> serde_json::Value {
        json!({
            "method": self.method,
            "path": self.path,
            "category": self.category,
            "owner": self.owner,
            "auth_required": true,
            "control_plane_role": "read-only-observer",
            "mutates_ao_artifacts": false,
            "mutates_observer_storage": self.mutates_observer_storage,
            "control_plane_approves_release": false,
            "download": self.download,
            "portable": self.portable,
        })
    }
}

pub const ROUTES: &[RouteMetadata] = &[
    RouteMetadata {
        method: "GET",
        path: "/api/v1/acceptance",
        category: "acceptance-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/acceptance",
        category: "acceptance-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/acceptance/dashboard",
        category: "acceptance-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/acceptance/dashboard.json",
        category: "acceptance-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/acceptance/:sha",
        category: "acceptance-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/acceptance/:sha",
        category: "acceptance-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/control-plane/bundle",
        category: "observer-ingest",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/control-plane/bundle",
        category: "observer-list",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/control-plane/bundle/:sha",
        category: "observer-list",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/control-plane/bundle/:sha",
        category: "observer-list",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/control-plane/routes.json",
        category: "route-index",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/evidence-pack",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/evidence-pack/dashboard",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/evidence-pack/dashboard.json",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/evidence-pack/signed",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/evidence-pack/run/:run_id/latest",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/evidence-pack/:sha/detail",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/evidence-pack/:sha/detail.json",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/evidence-pack/:sha/signature",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/evidence-pack/:sha",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/evidence-pack/:sha",
        category: "signed-evidence-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/hermes/watchdog/panel",
        category: "hermes-watchdog-observer",
        owner: "factory-v3 Hermes watchdog",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/hermes/watchdog/panel",
        category: "hermes-watchdog-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/hermes/watchdog/panel/latest.json",
        category: "hermes-watchdog-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/hermes/watchdog/history.json",
        category: "hermes-watchdog-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/memory/export",
        category: "memory-export-observer",
        owner: "ao2 signed memory boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/memory/export",
        category: "memory-export-observer",
        owner: "ao2 signed memory boundary",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/memory/export/dashboard",
        category: "memory-export-observer",
        owner: "ao2 signed memory boundary",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/memory/export/signed",
        category: "memory-export-observer",
        owner: "ao2 signed memory boundary",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/memory/export/:sha/signature",
        category: "memory-export-observer",
        owner: "ao2 signed memory boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/memory/export/:sha",
        category: "memory-export-observer",
        owner: "ao2 signed memory boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/memory/export/:sha",
        category: "memory-export-observer",
        owner: "ao2 signed memory boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/dashboard",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/dashboard.json",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/operator-panel",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/operator-panel.json",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/gap-report.json",
        category: "phase1-gap-report",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/gap-report/download",
        category: "phase1-gap-report",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/gap-report/SHA256SUMS",
        category: "phase1-gap-report",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/operator-support-bundle.json",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/operator-support-bundle/download",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/operator-support-bundle/SHA256SUMS",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/phase1/promotion/operator-support-bundle/verify",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/phase1/promotion/operator-support-bundle/verify.json",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/portable-manifest",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/portable-manifest.json",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/portable-manifest/download",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/portable-manifest/SHA256SUMS",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/phase1/promotion/portable-manifest/verify",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/phase1/promotion/portable-manifest/verify.json",
        category: "phase1-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/history.json",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/phase1/promotion/three-os-smoke",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/three-os-smoke/latest",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/three-os-smoke/:sha",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/phase1/promotion/three-os-smoke/:sha",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/phase1/promotion/checklist",
        category: "phase1-readiness",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/checklist/latest",
        category: "phase1-readiness",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/checklist/:sha",
        category: "phase1-readiness",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/phase1/promotion/checklist/:sha",
        category: "phase1-readiness",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/phase1/promotion/inputs-verification",
        category: "phase1-readiness",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/inputs-verification/latest",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/inputs-verification/:sha",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/phase1/promotion/inputs-verification/:sha",
        category: "phase1-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/phase1/promotion/decision/signed",
        category: "phase1-readiness",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/decision/latest",
        category: "phase1-readiness",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/decision/:sha",
        category: "phase1-readiness",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/phase1/promotion/decision/:sha",
        category: "phase1-readiness",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/phase1/promotion/decision/:sha/signature",
        category: "phase1-readiness",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/registry",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/provider/registry",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/registry/dashboard",
        category: "provider-registry-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/registry/dashboard.json",
        category: "provider-registry-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/provider/registry/signed",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/registry/latest",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/provider/registry/latest",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/registry/:sha/detail",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/registry/:sha/detail.json",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/registry/:sha/signature",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/registry/:sha",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/provider/registry/:sha",
        category: "provider-registry-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness",
        category: "provider-readiness-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/provider/readiness",
        category: "provider-readiness-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/dashboard",
        category: "provider-readiness-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/dashboard.json",
        category: "provider-readiness-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/provider/readiness/signed",
        category: "provider-readiness-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/latest",
        category: "provider-readiness-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/support-bundle.json",
        category: "provider-readiness-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/support-bundle/download",
        category: "provider-readiness-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/support-bundle/SHA256SUMS",
        category: "provider-readiness-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/:sha/detail",
        category: "provider-readiness-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/:sha/detail.json",
        category: "provider-readiness-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/:sha/signature",
        category: "provider-readiness-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/provider/readiness/:sha",
        category: "provider-readiness-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/provider/readiness/:sha",
        category: "provider-readiness-observer",
        owner: "ao2 signed evidence boundary",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/release/publication",
        category: "release-publication-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/cockpit",
        category: "release-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/cockpit.json",
        category: "release-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/handoff",
        category: "release-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/handoff.json",
        category: "release-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/readiness",
        category: "release-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/readiness.json",
        category: "release-readiness",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/support-bundle.json",
        category: "release-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/support-bundle/manifest",
        category: "release-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/support-bundle/manifest.json",
        category: "release-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/support-bundle/download",
        category: "release-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/support-bundle/SHA256SUMS",
        category: "release-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/support-bundle/verify",
        category: "release-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/support-bundle/verify.json",
        category: "release-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/support-bundle/handoff",
        category: "release-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/support-bundle/handoff.json",
        category: "release-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/release/evaluator-decision",
        category: "release-acceptance-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/release/evaluator-decision/signed",
        category: "release-acceptance-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/evaluator-decision/latest",
        category: "release-acceptance-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/evaluator-decision/:sha",
        category: "release-acceptance-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/release/evaluator-decision/:sha",
        category: "release-acceptance-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/evaluator-decision/:sha/signature",
        category: "release-acceptance-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/evaluator-decision/dashboard",
        category: "release-acceptance-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/evaluator-decision/dashboard.json",
        category: "release-acceptance-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/publication/latest",
        category: "release-publication-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/publication/:sha",
        category: "release-publication-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "HEAD",
        path: "/api/v1/release/publication/:sha",
        category: "release-publication-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/publication/dashboard",
        category: "release-publication-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/release/publication/dashboard.json",
        category: "release-publication-observer",
        owner: "factory-v3 evaluator-closer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/storage/report",
        category: "storage-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/storage/dashboard",
        category: "storage-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/storage/dashboard.json",
        category: "storage-observer",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/storage/support-bundle.json",
        category: "storage-support-bundle",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/storage/support-bundle/download",
        category: "storage-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/storage/support-bundle/contract.json",
        category: "storage-support-bundle-contract",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/storage/support-bundle/SHA256SUMS",
        category: "storage-support-bundle",
        owner: "ao2-control-plane observer",
        download: true,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "POST",
        path: "/api/v1/storage/prune",
        category: "storage-retention",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: true,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/metrics",
        category: "metrics",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/status",
        category: "status",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/healthz/extended",
        category: "status",
        owner: "ao2-control-plane observer",
        download: false,
        portable: true,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/audit-log",
        category: "audit",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/audit-log/stream",
        category: "audit",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/audit-log/dashboard",
        category: "audit",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
    RouteMetadata {
        method: "GET",
        path: "/api/v1/audit-log/dashboard.json",
        category: "audit",
        owner: "ao2-control-plane observer",
        download: false,
        portable: false,
        mutates_observer_storage: false,
    },
];

pub fn route_index_entries() -> Vec<serde_json::Value> {
    ROUTES.iter().copied().map(RouteMetadata::to_json).collect()
}

pub fn portable_artifact_groups() -> Vec<serde_json::Value> {
    vec![
        json!({
            "id": "phase1_gap_report",
            "schema_version": "ao2.cp-phase1-gap-report.v1",
            "description": "Machine-readable Phase 1 blocking gap report for schedulers and operator handoff.",
            "owner": "ao2-control-plane observer",
            "release_acceptance_owner": "factory-v3 evaluator-closer",
            "mutates_ao_artifacts": false,
            "control_plane_approves_release": false,
            "credential_material_in_urls": false,
            "links": {
                "json": "/api/v1/phase1/promotion/gap-report.json",
                "download": "/api/v1/phase1/promotion/gap-report/download",
                "checksums": "/api/v1/phase1/promotion/gap-report/SHA256SUMS"
            }
        }),
        json!({
            "id": "phase1_operator_support_bundle",
            "schema_version": "ao2.cp-phase1-operator-support-bundle.v1",
            "description": "Portable Phase 1 operator support bundle for observer-only promotion review.",
            "owner": "ao2-control-plane observer",
            "release_acceptance_owner": "factory-v3 evaluator-closer",
            "mutates_ao_artifacts": false,
            "control_plane_approves_release": false,
            "credential_material_in_urls": false,
            "links": {
                "json": "/api/v1/phase1/promotion/operator-support-bundle.json",
                "download": "/api/v1/phase1/promotion/operator-support-bundle/download",
                "checksums": "/api/v1/phase1/promotion/operator-support-bundle/SHA256SUMS",
                "portable_manifest": "/api/v1/phase1/promotion/portable-manifest",
                "portable_manifest_json": "/api/v1/phase1/promotion/portable-manifest.json",
                "portable_manifest_download": "/api/v1/phase1/promotion/portable-manifest/download",
                "portable_manifest_checksums": "/api/v1/phase1/promotion/portable-manifest/SHA256SUMS"
            }
        }),
        json!({
            "id": "provider_readiness_support_bundle",
            "schema_version": "ao2.cp-provider-readiness-support-bundle.v1",
            "description": "Portable provider-readiness observer bundle for evaluator handoff.",
            "owner": "ao2-control-plane observer",
            "release_acceptance_owner": "factory-v3 evaluator-closer",
            "mutates_ao_artifacts": false,
            "control_plane_approves_release": false,
            "credential_material_in_urls": false,
            "links": {
                "json": "/api/v1/provider/readiness/support-bundle.json",
                "download": "/api/v1/provider/readiness/support-bundle/download",
                "checksums": "/api/v1/provider/readiness/support-bundle/SHA256SUMS"
            }
        }),
        json!({
            "id": "storage_support_bundle",
            "schema_version": "ao2.cp-support-bundle.v1",
            "description": "Portable observer-retention and Phase 1 readiness storage support bundle.",
            "owner": "ao2-control-plane observer",
            "release_acceptance_owner": "factory-v3 evaluator-closer",
            "mutates_ao_artifacts": false,
            "control_plane_approves_release": false,
            "credential_material_in_urls": false,
            "links": {
                "json": "/api/v1/storage/support-bundle.json",
                "download": "/api/v1/storage/support-bundle/download",
                "checksums": "/api/v1/storage/support-bundle/SHA256SUMS",
                "contract_json": "/api/v1/storage/support-bundle/contract.json"
            }
        }),
        json!({
            "id": "release_support_bundle",
            "schema_version": "ao2.cp-release-support-bundle.v1",
            "description": "Portable release support bundle with embedded same-candidate surfaces and offline digest verification.",
            "owner": "ao2-control-plane observer",
            "release_acceptance_owner": "factory-v3 evaluator-closer",
            "mutates_ao_artifacts": false,
            "control_plane_approves_release": false,
            "credential_material_in_urls": false,
            "links": {
                "json": "/api/v1/release/support-bundle.json",
                "manifest": "/api/v1/release/support-bundle/manifest",
                "manifest_json": "/api/v1/release/support-bundle/manifest.json",
                "download": "/api/v1/release/support-bundle/download",
                "checksums": "/api/v1/release/support-bundle/SHA256SUMS",
                "verify": "/api/v1/release/support-bundle/verify",
                "verify_json": "/api/v1/release/support-bundle/verify.json",
                "verifier_handoff": "/api/v1/release/support-bundle/handoff",
                "verifier_handoff_json": "/api/v1/release/support-bundle/handoff.json"
            }
        }),
    ]
}
